//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using System.Linq;
    using System.Data.Entity;

    public partial class Wit_NavBar : WitDbContextBase<Wit_NavBar>, IWit_NavBar
    {
        public List<Wit_NavBar> GetNavBar(string userUID)
        {
            db.Configuration.AutoDetectChangesEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;

            //Initial Get
            var navBar = db.Wit_NavBar.Where(m => m.Menu == Wit_Menu.MyProfile);

            List<AspNetRole> roles = db.AspNetRoles.Where(m => m.AspNetUsers.Any(user => user.Id == userUID)).ToList();

            foreach (AspNetRole role in roles)
            {
                if (!role.IsGuest())
                {
                    if (role.IsPowerUser())
                    {
                        navBar = navBar.Union(
                                 db.Wit_NavBar.Where(m => m.Menu == Wit_Menu.AdminMaintenance));
                    }
                    navBar = navBar.Union(
                         db.Wit_NavBar.Where(m => m.Menu == Wit_Menu.MobileAdministrator));
                }
            }

            return navBar.ToList();
        }

        public void Dispose()
        {
            GC.Collect();
            db.Dispose();
        }
    }
}
