//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WitDbContext : DbContext
    {
        public WitDbContext()
            : base("name=WitDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Wit_Category> Wit_Category { get; set; }
        public virtual DbSet<Wit_Company> Wit_Company { get; set; }
        public virtual DbSet<Wit_Item> Wit_Item { get; set; }
        public virtual DbSet<Wit_Order> Wit_Order { get; set; }
        public virtual DbSet<Wit_Table> Wit_Table { get; set; }
        public virtual DbSet<Wit_Transaction> Wit_Transaction { get; set; }
        public virtual DbSet<Wit_User> Wit_User { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Wit_NavBar> Wit_NavBar { get; set; }
        public virtual DbSet<UsersViewModel> UsersViewModels { get; set; }
        public virtual DbSet<Wit_Session> Wit_Session { get; set; }
    }
}
