//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wit_Category
    {
        public Wit_Category()
        {
            this.Wit_Item = new HashSet<Wit_Item>();
        }
    
        public System.Guid Category_UID { get; set; }
        public System.Guid Company_UID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Wit_Company Wit_Company { get; set; }
        public virtual ICollection<Wit_Item> Wit_Item { get; set; }
    }
}
