//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wit_Item
    {
        public Wit_Item()
        {
            this.Wit_Order = new HashSet<Wit_Order>();
        }
    
        public System.Guid Item_UID { get; set; }
        public System.Guid Category_UID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string ImageURL { get; set; }
        public bool OnStock { get; set; }
        public string SpiceLevel { get; set; }
        public Nullable<int> Likes { get; set; }
        public string FoodMark { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public Nullable<bool> IsBestSeller { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Wit_Category Wit_Category { get; set; }
        public virtual ICollection<Wit_Order> Wit_Order { get; set; }
    }
}
