//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wit_Company
    {
        public Wit_Company()
        {
            this.Wit_Category = new HashSet<Wit_Category>();
            this.Wit_Status = new HashSet<Wit_Status>();
            this.Wit_Table = new HashSet<Wit_Table>();
            this.Wit_User = new HashSet<Wit_User>();
        }
    
        public System.Guid Company_UID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyNumber { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Wit_Category> Wit_Category { get; set; }
        public virtual ICollection<Wit_Status> Wit_Status { get; set; }
        public virtual ICollection<Wit_Table> Wit_Table { get; set; }
        public virtual ICollection<Wit_User> Wit_User { get; set; }
    }
}
