//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wit_Order
    {
        public System.Guid Order_UID { get; set; }
        public System.Guid Transaction_UID { get; set; }
        public System.Guid Item_UID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Wit_Item Wit_Item { get; set; }
        public virtual Wit_Transaction Wit_Transaction { get; set; }
    }
}
