//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wit_NavBar
    {
        public Wit_NavBar()
        {
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public System.Guid NavBar_UID { get; set; }
        public string Menu { get; set; }
        public string SubMenu { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
