//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wit_UserRole
    {
        public System.Guid UserRole_UID { get; set; }
        public System.Guid Role_UID { get; set; }
        public System.Guid User_UID { get; set; }
    
        public virtual Wit_Role Wit_Role { get; set; }
        public virtual Wit_User Wit_User { get; set; }
    }
}
