//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wit_Session
    {
        public System.Guid Session_UID { get; set; }
        public System.Guid User_UID { get; set; }
        public string Browser { get; set; }
        public string DeviceType { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Wit_User Wit_User { get; set; }
    }
}
